n_channels: 63
pre_norm_shift: true
pre_norm_scale: true
pre_norm_affine: false
pre_norm_bias: false
expert_encoder_conv1_kernel_size: 3
expert_encoder_conv1_padding: 1
expert_encoder_conv1_dilation: 0
expert_encoder_conv2_kernel_size: 3
expert_encoder_conv2_padding: 1
expert_encoder_conv2_dilation: 0
expert_encoder_n_input_samples: 100
expert_encoder_block_size: 100
expert_encoder_d_model: 1280 
expert_encoder_n_heads: 16
expert_encoder_n_layers: 2
expert_encoder_bias: true
expert_encoder_dropout: 0.1
tokenizer_path: gpt2-large
pretrained_gpt: gpt2-large
freeze_gpt: true
gpt_start_token: 3784
gpt_stop_token: 50256
gpt_block_size: 107
gpt_dropout: 0.1
