n_eeg_channels: 63
text_encoder_pretrained_model: sentence-transformers/sentence-t5-large
neural_encoder_block_size: 400
text_encoder_block_size: 10
d_model: 1024
shared_emb_dim: 768
neural_encoder_d_mlp: 3072
text_encoder_d_mlp: 2816
text_encoder_vocab_size: 32128
n_heads: 16
neural_encoder_n_layers: 24
text_encoder_n_layers: 24
dropout: 0.1
cache_text_embeddings: True
neural_encoder_checkpoint_activations: True
