dtype: bf16
dataset_path: data/
subjects:
  - 1
things_metadata_path: data/things_concepts.csv
num_epochs: 100
batch_size: 768
train_micro_batch_size: 128
val_micro_batch_size: 128
validation_interval: 1.0
log_interval: 1
max_lr: 0.0001
weight_decay: 0.00001
warmup_frac: 0.01
grad_clip: 1.0
