dtype: fp32
dataset_path: data/things_eeg_100ms
subjects:
  - 1
things_metadata_path: data/things_eeg_100ms/things_concepts.csv
num_epochs: 1
batch_size: 8
micro_batch_size: 2
validation_interval: 0.1
log_interval: 1
max_lr: 0.00001
weight_decay: 0.000001
warmup_frac: 0.05
grad_clip: 1.0
